# -*- coding: utf-8 -*-
"""Process image data for Deep Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5uK7hAeCpPHgXl_88o8jvrRvqtLj7_o
"""

# GETTING IMAGE USING WEBGET COMMAND
!wget "https://i.pinimg.com/1200x/1e/05/c7/1e05c70d05a867527a95a41c36b6e6a8.jpg"

"""**Libraries that can be used in image processing**

1. matplotlib.image
2. pillow
3. openCV (computer vision)
"""

# IMPORT MATPLOTLIB LIBRARIE FOR IMAGE PROCESS
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

img = mpimg.imread("Lional_Messi.jpg")
type(img)

img.shape  # height , width , channel count (1 channel / 3 channel)

print(img)

